#!/usr/bin/env python3
"""
Demo script showing the new cluster viewing functionality
"""

print("🚀 MongoDB Atlas Projects Manager - New Cluster View Feature")
print("=" * 60)
print()
print("✨ NEW FEATURES ADDED:")
print()
print("1. 🔍 **Cluster View**: Click on any project to see its clusters")
print("   - View cluster status, provider, region, and instance size")
print("   - See MongoDB version for each cluster")
print("   - Navigate back with Escape or 'b' key")
print()
print("2. 🖱️  **Interactive Navigation**:")
print("   - Mouse support: Click on project rows")
print("   - Keyboard support: Arrow keys + Enter")
print("   - Intuitive back navigation")
print()
print("3. 📊 **Enhanced Project Table**:")
print("   - Streamlined view with essential information")
print("   - Better visual indicators")
print("   - Improved status messages")
print()
print("📋 **How to Use:**")
print("   1. Run: python3 atlas_projects_manager.py")
print("   2. Press 'a' to authenticate and load projects")
print("   3. Click on any project row OR select and press Enter")
print("   4. View detailed cluster information")
print("   5. Press Escape to return to projects view")
print()
print("🔧 **Requirements:**")
print("   - Valid MongoDB Atlas API credentials in .env file")
print("   - Python 3.8+ with required dependencies")
print("   - Active Atlas projects with clusters")
print()
print("💡 **Tip**: The application now provides two-level navigation:")
print("    Projects → Clusters → Back to Projects")
print()
print("=" * 60)
print("🎉 Ready to explore your Atlas infrastructure!")